version: '3'
services:
  database:
    image: postgres:11
    ports:
      - "5432:5432"
  cache:
    image: redis:3
    ports:
      - "6379:6379"
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
