name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Start services
      run: docker-compose up -d
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
    - name: Setup database
      run: |
        bundle exec db:setup
    - name: Compile Webpack
      run: |
        bundle exec webpacker:compile
    - name: Build and test with Rake
      run: |
        bundle exec standardrb --no-fix
        bundle exec rake test
