name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libpq-dev
        gem install bundler --no-doc
        bundle install --jobs 4 --retry 3
    - name: Start services
      run: docker-compose up -d
    - name: Setup database
      run: |
        bundle exec db:setup
    - name: Compile Webpack
      run: |
        bundle exec webpacker:compile
    - name: Build and test with Rake
      run: |
        bundle exec standardrb --no-fix
        bundle exec rake test
